apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-app-deployment
  labels:
    app: patient
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patient
  template:
    metadata:
      labels:
        app: patient
    spec:
      containers:
      - name: patient-app
        image: mohitmajhi/patient:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: patient-service
spec:
  type: NodePort
  selector:
    app: patient
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30100


